name: Deploy Texefa to LWS

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to LWS via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync files to LWS FTP
        uses: SamKirsch/ftp-deploy@v1.2.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./
